-- 기존 테이블 및 시퀀스 삭제
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOSPITAL_ACCOUNT CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE HOSPITAL_INFO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE MEDICAL_FIELD CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE MEMBER CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DOCTOR_REVIEW CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE RESERVATION CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TREATMENT CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BOARD CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FILE_TABLE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE COMMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 기존 시퀀스 삭제
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HOS_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RES_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TREATMENT_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOARD_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REVIEW_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FILE_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MED_NO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOARD_VIEWS';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REVIEW_VIEWS';

EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 시퀀스 생성
CREATE SEQUENCE SEQ_HOS_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RES_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USER_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TREATMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FILE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MED_NO START WITH 1 INCREMENT BY 1 NOCACHE;


-- 조회수 시퀀스: 0부터 시작
CREATE SEQUENCE SEQ_BOARD_VIEWS START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_VIEWS START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE;


-- 테이블 생성
CREATE TABLE HOSPITAL_ACCOUNT (
    HOS_NO NUMBER NOT NULL PRIMARY KEY,
    HOS_ID VARCHAR2(20) NOT NULL,
    HOS_PWD VARCHAR2(20) NOT NULL,
    HOS_NAME VARCHAR2(50) NOT NULL,
    HOS_ADDRESS VARCHAR2(200) NOT NULL,
    HOS_TEL VARCHAR2(20) NOT NULL,
    HOS_YEAR DATE,
    HOS_TIME VARCHAR2(20),
    HOS_INFO VARCHAR2(2000),
    HOS_ONDUTY VARCHAR2(20),
    HOS_PARKING VARCHAR2(100)
);

CREATE TABLE HOSPITAL_INFO (
    HOS_NO NUMBER NOT NULL PRIMARY KEY,
    HOS_NAME VARCHAR2(250),
    HOS_ADDRESS VARCHAR2(250),
    HOS_TEL VARCHAR2(20),
    DEPARTMENT VARCHAR2(250),
    HOS_START_TIME1 NUMBER,
    HOS_CLOSE_TIME1 NUMBER,
    HOS_START_TIME2 NUMBER,
    HOS_CLOSE_TIME2 NUMBER,
    HOS_LATITUDE NUMBER,
    HOS_LONGITUDE NUMBER,
    FOREIGN KEY (HOS_NO) REFERENCES HOSPITAL_ACCOUNT (HOS_NO)
);

CREATE TABLE MEDICAL_FIELD (
    MED_NO NUMBER NOT NULL PRIMARY KEY,
    JOB VARCHAR2(50) NOT NULL,
    MEDICAL_FIELD_ID VARCHAR2(20) NOT NULL
);

CREATE TABLE MEMBER (
    USER_NO NUMBER NOT NULL PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    GENDER CHAR(1) DEFAULT 'M' CHECK (GENDER IN ('M', 'F')),
    ADDRESS VARCHAR2(200),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    ISADMIN VARCHAR2(10) DEFAULT 'N',
    MED_KEY NUMBER,
    HOS_NO NUMBER,
    FOREIGN KEY (MED_KEY) REFERENCES MEDICAL_FIELD (MED_NO),
    FOREIGN KEY (HOS_NO) REFERENCES HOSPITAL_ACCOUNT (HOS_NO)
);

CREATE TABLE DOCTOR_REVIEW (
    REVIEW_NO NUMBER NOT NULL PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    REVIEW_TITLE VARCHAR2(200) NOT NULL,
    REVIEW_CONTENT VARCHAR2(2000) NOT NULL,
    REVIEW_CREATED_AT DATE DEFAULT SYSDATE,
    REVIEW_UPDATED_AT DATE DEFAULT SYSDATE,
    REVIEW_VIEWS NUMBER DEFAULT 0,
    REVIEW_RATING NUMBER,
    USER_ID2 VARCHAR2(20),
    FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

CREATE TABLE RESERVATION (
    RES_NO NUMBER NOT NULL PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    HOS_NO NUMBER NOT NULL,
    RES_DATE DATE DEFAULT SYSDATE,
    RES_TIME DATE NOT NULL,
    RES_CATEGORY VARCHAR2(20) NOT NULL,
    RES_CONTENT VARCHAR2(2000),
    FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO),
    FOREIGN KEY (HOS_NO) REFERENCES HOSPITAL_ACCOUNT (HOS_NO)
);

CREATE TABLE TREATMENT (
    TREATMENT_NO NUMBER NOT NULL PRIMARY KEY,
    RES_NO NUMBER NOT NULL,
    VACCINE_CATEGORY VARCHAR2(20),
    HEALTH_SELECT VARCHAR2(20),
    RES_SELECT VARCHAR2(20),
    FOREIGN KEY (RES_NO) REFERENCES RESERVATION (RES_NO)
);

CREATE TABLE BOARD (
    BOARD_NO NUMBER NOT NULL PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    VIEWS NUMBER DEFAULT 0,
    BOARD_CATEGORY VARCHAR2(20),
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

CREATE TABLE FILE_TABLE (
    FILE_NO NUMBER NOT NULL PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(200),
    CHANGE_NAME VARCHAR2(200),
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD (BOARD_NO),
    FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

CREATE TABLE COMMENTS (
    COMMENT_NO NUMBER NOT NULL PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    CONTENT VARCHAR2(2000),
    CREATED_AT DATE DEFAULT SYSDATE,
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD (BOARD_NO),
    FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);
